version: '3.8'

services:
  descargas:
    build:
      context: .
      dockerfile: Dockerfile.descargas

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8501:8501"
    volumes:
      - ./web:/app/web
      - ./data_clasificaciones:/app/data_clasificaciones
      - ./datos_resultados:/app/datos_resultados
      - ./data_jugadores:/app/data_jugadores
      - ./data_fifa:/app/data_fifa
    depends_on:
      - descargas