FROM python:3.11-slim

WORKDIR /app

# El contenedor arranca, avisa de que se salta todo y termina con éxito (code 0)
CMD ["echo", "[INFO] Los scripts se han ejecutado desde fuera. Saltando descargas en Docker por completo."]