FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY web/ ./web/

WORKDIR /app/web

CMD ["streamlit", "run", "MENÚ.py", "--server.port=8501", "--server.address=0.0.0.0"]